### ISSUE TITLE
Could not find ffi-1.9.17 in any of the sources

### ISSUE THREAD

**Issue by tayler-ramsay** [core77/jekyll-foundation#49]
Sorry I am very new so if this is a easy fix I apologize. When I run NPM start I keep getting these errors.

[09:11:47] Using gulpfile ~/Desktop/foundation/g_connect/jekyll-foundation/gulpfile.js
[09:11:47] Starting 'default'...
[09:11:47] Starting 'build'...
[09:11:47] Starting 'clean'...
[09:11:47] Finished 'clean' after 3.17 ms
[09:11:47] Starting 'jekyll-build'...
Could not find ffi-1.9.17 in any of the sources
Run `bundle install` to install missing gems.
[09:11:48] 'jekyll-build' errored after 531 ms
[09:11:48] Error: 7
    at formatError (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/orchestrator/index.js:264:8)
    at /Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/orchestrator/index.js:275:23
    at finish (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/orchestrator/lib/runTask.js:29:3)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
[09:11:48] 'default' errored after 538 ms
[09:11:48] Error in plugin 'run-sequence(jekyll-build)'
Error
    at finish (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/run-sequence/index.js:67:4)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/orchestrator/index.js:264:8)
    at /Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/orchestrator/index.js:275:23
    at finish (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/orchestrator/lib/runTask.js:29:3)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
[09:11:48] 'build' errored after 538 ms
[09:11:48] Error in plugin 'run-sequence(default)'
Error
    at finish (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/run-sequence/index.js:67:4)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/orchestrator/index.js:264:8)
    at /Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/orchestrator/index.js:275:23
    at finish (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/run-sequence/index.js:60:5)
    at Gulp.onError (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/run-sequence/index.js:67:4)
[09:11:48] 'build' errored after 538 ms
[09:11:48] Error in plugin 'run-sequence(jekyll-build)'
Error
    at finish (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/run-sequence/index.js:67:4)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/orchestrator/index.js:264:8)
    at /Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/orchestrator/index.js:275:23
    at finish (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/orchestrator/lib/runTask.js:29:3)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! jekyll-foundation@0.4.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jekyll-foundation@0.4.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jekyll-foundation package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jekyll-foundation
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jekyll-foundation
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.3
3 info using node@v6.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle jekyll-foundation@0.4.0~prestart: jekyll-foundation@0.4.0
6 silly lifecycle jekyll-foundation@0.4.0~prestart: no script for prestart, continuing
7 info lifecycle jekyll-foundation@0.4.0~start: jekyll-foundation@0.4.0
8 verbose lifecycle jekyll-foundation@0.4.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle jekyll-foundation@0.4.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation/node_modules/.bin:/usr/local/bin:/Users/Tayler_Ramsay/.rvm/gems/ruby-2.2.3/bin:/Users/Tayler_Ramsay/.rvm/gems/ruby-2.2.3@global/bin:/Users/Tayler_Ramsay/.rvm/rubies/ruby-2.2.3/bin:/Users/Tayler_Ramsay/.rvm/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin
10 verbose lifecycle jekyll-foundation@0.4.0~start: CWD: /Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation
11 silly lifecycle jekyll-foundation@0.4.0~start: Args: [ '-c', 'gulp' ]
12 silly lifecycle jekyll-foundation@0.4.0~start: Returned: code: 1  signal: null
13 info lifecycle jekyll-foundation@0.4.0~start: Failed to exec start script
14 verbose stack Error: jekyll-foundation@0.4.0 start: `gulp`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid jekyll-foundation@0.4.0
16 verbose cwd /Users/Tayler_Ramsay/Desktop/foundation/g_connect/jekyll-foundation
17 error Darwin 16.4.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.5.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error jekyll-foundation@0.4.0 start: `gulp`
22 error Exit status 1
23 error Failed at the jekyll-foundation@0.4.0 start script 'gulp'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the jekyll-foundation package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs jekyll-foundation
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls jekyll-foundation
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

I am using rvm so I don't know if that is effecting it

Thank you for any help you can offer.

**Comment by tayler-ramsay** [comment]
Sorry I just had to update my npm and node
